dinos_app/config/routes.rb
Rails.application.routes.draw do
  get 'dinos/index'

  get 'dinos/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/welcome', to: 'welcome#index'
  resources :dinos
end

dinos_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

dinos_app/app/models/dino.rb
class Dino < ApplicationRecord
end

dinos_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

dinos_app/app/controllers/dinos_controller.rb
class DinosController < ApplicationController

  before_action :set_dino, only: [:show, :edit, :update, :destroy]
  def index
    # you need to get all Dinos from the database
    @dinos = Dino.all
  end

  def show
    @dino = Dino.find(params[:id])
  end

  def new
    @dino = Dino.new
  end

  def create
    @dino = Dino.new(dino_params)

    respond_to do |format|
      if @dino.save
        format.html { redirect_to @dino, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @dino }
      else
        format.html { render :new }
        format.json{ render json: @dino.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @dino
  end

  def edit
  end

  def update
    respond_to do |format|
      if @dino.update(dino_params)
        format.html { redirect_to @dino, notice: 'Post was successfully updated.' }
      else
        format.html {render :edit }
      end
    end
  end

  def destroy
    @dino.destroy
    respond_to do |format|
      format.html { redirect_to dinos_url, notice: 'Post was successfully destroyed'}
      format.json { head :no_content }
    end
  end

  private
  # User callbacks to share common setup or constraints between actions.
  # get the :id params from the url to be passed to each action
  def set_dino
    @dino = Dino.find(params[:id])
  end

  # params object is being generated on every form to be passed to the corresponding
  # never trust parameters from the scary internet, only allow the white list through
  def dino_params
    params.require(:dino).permit(:name, :color, :breed)
  end

end

dinos_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

dinos_app/app/helpers/application_helper.rb
module ApplicationHelper
end

dinos_app/app/helpers/dinos_helper.rb
module DinosHelper
end

dinos_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

dinos_app/app/views/dinos/_form.html.erb
<%= form_for(@dino) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_area :color %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_area :breed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

dinos_app/app/views/dinos/edit.html.erb
<h1>Form to edit dino</h1>
<%= render partial: 'form' %>

dinos_app/app/views/dinos/index.html.erb
<div class="container">
  <h1>This is DINOS view !!!</h1>
  <h2> sooooooo, here you go: 🐉 🐉 🐉 🐉 🐉 🐉 🐉 🐉 🐉 </h2>

<!-- [TO DO: ] insert the logic to render all dinos as from the database passe from the index action -->
<!-- Each dino should be a link to a show page for that particular dino  -->



  <img src="https://thumbs.dreamstime.com/x/cute-green-dinosaur-cartoon-illustration-33993033.jpg" alt="dino pic">
</br>
  <p><%= link_to "Create new dino", new_dino_path %></p>
  <p><%= link_to "Back to home page", welcome_path %></p>
</div>
</br>
  <% @dinos.each do |dino|%>
    <h1><%= link_to dino.name, dino_path(dino) %></h1>
  <%end%>
</br>

dinos_app/app/views/dinos/new.html.erb
<h1>create a new dino</h1>
<%= render partial: 'form'%>

dinos_app/app/views/dinos/show.html.erb
<div class="container">
  <h1>Hello! This is the dino you requested:
  <h1><span><%= @dino.name %></span></h1>
  <h1><span><%= @dino.color %></span></h1>
  <h1><span><%= @dino.breed %></span></h1>
  </h1>
  <%= link_to("edit dino", edit_dino_path) %>
  </br>
  <%= link_to 'delete dino', dino_path(@dino), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

dinos_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinosApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
    <h1>My Website for Dinos!</h1>
    <ul>
      <li><%= link_to 'See all Dinos', dinos_path %></li>
      <li>Maybe some other menu item</li>
      <li>And another menu item</li>
    </ul>
  </header>
  <%= yield %>
    <footer>
      <ul>
        <li>About us</li>
        <li>Team</li>
        <li>Terms and conditions</li>
      </ul>
    </footer>
  </body>
</html>

dinos_app/app/views/welcome/index.html.erb
<h1><%= link_to "Welcome to Dino's app", dinos_path %></h1>